### ISSUE TITLE
the game crashes on startup

### ISSUE THREAD

**Issue by alfabe78h** [aBARICHELLO/Firewatch-noclip#4]
Hello im having this error here im using windows 10 and when is start the game it gives a black screen for a couple of seconds then it crashes here is the error log: 
[error.txt](https://github.com/abarichello/Firewatch-noclip/files/11359984/error.txt)

**Comment by abarichello** [comment]
Hi, this mod has been deprecated. It used to work on earlier versions of the game but I can't guarantee that it will work on current or future updates.
